const actionTypes = {
  ADD_TO_CART: 'ADD_TO_CART',
  RESET_CART: 'RESET_CART',
  TOGGLE_MENU_CART: 'TOGGLE_MENU_CART',
  DELETE_TO_CART: 'DELETE_TO_CART',
  SET_BUY: 'SET_BUY',
  CLEAR_BUY: 'CLEAR_BUY',
};

export default actionTypes;